name: holoworld
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-12.1.0
  - xformers
dependencies:
  - python=3.11
  - pip
  - pytorch::pytorch=2.3.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1
  - nvidia/label/cuda-12.1.0::cuda-nvcc
  - datasets  
  - transformers 
  - xformers::xformers
  - conda-forge::jupyter  
  - pip:
    - autotrain-advanced